id: I2B43ABB1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:27:25+00:00'
last_modified: '2022-06-07T14:03:08.215571+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4232
  title: བཀའ་བརྒྱུད་ཆོས་འབྱུང་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3106':
      image_group_id: I1PD97696
      title: ''
      total_pages: 154
      order: 1
      base_file: 3106.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
