id: P001697
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4232
  title: བཀའ་བརྒྱུད་ཆོས་འབྱུང་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    7fcbee1f9a2440de9ad8bacbf6e71fb0:
      image_group_id: I1PD97696
      title: ''
      volume_number: 1
      total_pages: 154
